name: Chaos
version: '${project.version}'
main: lee.code.chaos.Chaos
api-version: 1.19
depend: [GoldmanCore, ProtocolLib]
commands:
  message:
    description: Message a online player.
    permission: chaos.command.message
    aliases: [msg, tell, whisper]
    usage: "/message &f<player> <message>"
  reply:
    description: Reply to a online player.
    permission: chaos.command.reply
    aliases: [r]
    usage: "/reply &f<message>"
  stats:
    description: Check your stats or a target player's stats.
    permission: chaos.command.stats
    usage: "/stats &f<player>"
  kits:
    description: Open the kit menu.
    permission: chaos.command.kits
    usage: "/kits"
  killstreaks:
    description: Open the kill streak menu.
    permission: chaos.command.killstreaks
    usage: "/killstreaks"
  addbooster:
    description: Add a coin booster.
    permission: chaos.command.addbooster
    usage: "/addbooster &f<player> <time> <multiplier>"
  booster:
    description: Checks booster status.
    permission: chaos.command.booster
    usage: "/booster"
  removebooster:
    description: Removes a booster from queue.
    permission: chaos.command.removebooster
    usage: "/removebooster &f<id>"